telegraf:
  image: telegraf:1.13.3
  container_name: default-telegraf
#  privileged: true
  restart: always
#  environment:
#    - HOST_PROC=/rootfs/proc
#    - HOST_SYS=/rootfs/sys
#    - HOST_MOUNT_PREFIX=/rootfs
#  net: host
  volumes:
#    - /:/rootfs:ro
#    - /proc:/rootfs/proc:ro
#    - /sys:/rootfs/sys:ro
    - /var/run/docker.sock:/var/run/docker.sock
   # - ./telegraf.conf:/etc/telegraf/telegraf.conf
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
#    - /home/webuser/dev/telegraf/log.file:/etc/telegraf/log.file
