version: "1"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/home/webuser/dev/influxdb
volume:
  influxdb-volume:
    external: true
